"""
agent/simulation/simulator.py

Spec section 32's simulation mode:
    incoming message -> decision -> generated reply -> timing ->
    permission -> action
    ...without actually sending anything.

This mirrors agent/reply/pipeline.py's real logic stage-by-stage, but
with one critical difference: it NEVER calls create_approval() (no
real approval queue entry is created) and never touches short-term
memory. Every stage is still genuinely executed — real candidates are
generated by the real model, the real quality checks run, the real
permission config and real timing engine are read — only the FINAL
side-effecting step (queuing a real approval) is replaced with "here
is what would have been queued."

This is why the report includes a full stage_trace: so you can see
exactly what happened at each step, not just a final verdict.
"""

from agent.brain.model_manager import get_active_model
from agent.personality.profile_store import load_profile
from agent.reply.context_builder import build_context_messages, build_system_prompt, resolve_contact_id
from agent.reply.candidate_generator import generate_candidates
from agent.reply.candidate_selector import select_best_candidate
from agent.reply.quality_check import run_quality_checks
from database.memory_store import get_recent_short_term
from agent.security.permission_engine import get_permission
from agent.timing.timing_engine import decide_timing


def simulate_incoming_message(incoming_message: str, contact_name: str | None = None) -> dict:
    """
    Runs the exact same decision chain as agent.reply.pipeline.generate_reply(),
    but never creates a real approval queue entry or writes to memory.

    Returns a dict with a "stage_trace" (list of {"stage": str, "detail": ...})
    for full visibility, plus a "final_status" describing what WOULD have
    happened: "would_send", "would_request_approval", "would_block",
    "would_wait" (timing), or "needs_review" (failed quality check).
    """
    trace = []
    model_name = get_active_model()
    contact_id = resolve_contact_id(contact_name)
    trace.append({"stage": "resolve_contact", "detail": f"contact_id={contact_id} (name={contact_name})"})

    context_messages = build_context_messages(contact_id=contact_id)
    trace.append({"stage": "build_context", "detail": f"{len(context_messages)} messages assembled (system prompt + recent history)"})

    candidates = generate_candidates(context_messages, incoming_message, model_name)
    trace.append({"stage": "generate_candidates", "detail": f"{len(candidates)} candidate(s) generated"})

    if not candidates:
        trace.append({"stage": "abort", "detail": "No candidates generated — is Ollama running?"})
        return {
            "final_status": "needs_review",
            "stage_trace": trace,
            "selected_text": "",
            "quality": None,
            "permission_level": None,
            "timing": None,
            "would_be_approval_payload": None,
        }

    style_summary = build_system_prompt(contact_id=contact_id)
    selection = select_best_candidate(candidates, style_summary, model_name)
    trace.append({
        "stage": "select_candidate",
        "detail": f"chose index {selection['selected_index']}: \"{selection['selected_text']}\" — {selection['reasoning']}",
    })

    profile = load_profile()
    recent = get_recent_short_term(limit=10, contact_id=contact_id)
    recent_agent_texts = [m["content"] for m in recent if m["role"] == "agent"]

    quality = run_quality_checks(selection["selected_text"], profile, recent_agent_texts, model_name)
    trace.append({
        "stage": "quality_check",
        "detail": f"passed={quality['passed']}, concerns={quality['concerns']}",
    })

    if not quality["passed"]:
        return {
            "final_status": "needs_review",
            "stage_trace": trace,
            "selected_text": selection["selected_text"],
            "quality": quality,
            "permission_level": None,
            "timing": None,
            "would_be_approval_payload": None,
        }

    permission_level = get_permission("send_normal_reply")
    trace.append({"stage": "permission_check", "detail": f"send_normal_reply = {permission_level}"})

    if permission_level in ("DISABLED", "NEVER"):
        trace.append({"stage": "outcome", "detail": "Blocked by permission — would not proceed to timing check."})
        return {
            "final_status": "would_block",
            "stage_trace": trace,
            "selected_text": selection["selected_text"],
            "quality": quality,
            "permission_level": permission_level,
            "timing": None,
            "would_be_approval_payload": None,
        }

    timing = decide_timing(contact_name)
    trace.append({"stage": "timing_check", "detail": f"allowed={timing['allowed']}, reason={timing['reason']}"})

    if not timing["allowed"]:
        trace.append({"stage": "outcome", "detail": "Blocked by timing (pause or sleep hours) — would not act, not even queue approval."})
        return {
            "final_status": "would_wait",
            "stage_trace": trace,
            "selected_text": selection["selected_text"],
            "quality": quality,
            "permission_level": permission_level,
            "timing": timing,
            "would_be_approval_payload": None,
        }

    would_be_payload = None
    if permission_level == "ASK":
        would_be_payload = {"draft_text": selection["selected_text"], "incoming_message": incoming_message}
        trace.append({"stage": "outcome", "detail": "Would create a real approval request (not created — this is a simulation)."})
        final_status = "would_request_approval"
    else:
        trace.append({"stage": "outcome", "detail": f"Would send after a {timing['delay_seconds']}s delay (AUTO/SUGGEST permission)."})
        final_status = "would_send"

    return {
        "final_status": final_status,
        "stage_trace": trace,
        "selected_text": selection["selected_text"],
        "quality": quality,
        "permission_level": permission_level,
        "timing": timing,
        "would_be_approval_payload": would_be_payload,
    }
